### ISSUE TITLE
cleaning CSV data for db seeding

### ISSUE THREAD

**Issue by rachelhamlin** [rachelhamlin/RecipeKeeper#1]
Hiii - I'm creating a recipes app & borrowed this list of ingredients: 

https://raw.githubusercontent.com/ginchly/recipe_parser/master/ingredients.csv

I pulled it into my own CSV file, stripped out the unnecessary stuff like "f" and "c" after an entry, and brought it into my Rails app under lib/seeds/ingredients.csv. 

But, I don't think the data is formatted correctly. I want to continue with seeding it according to these instructions: https://gist.github.com/arjunvenkat/1115bc41bf395a162084 -- just need to make sure it's going to work

**Comment by ajhofferber** [comment]
hey rachel, want to take a look at your issue?
